language: rust

matrix:
  include:
    - rust: stable
      env: CLANG_VERSION=clang_3_5 LLVM_CONFIG_PATH=/usr/lib/llvm-3.5/bin/llvm-config
      addons:
        apt:
          sources:
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.5
            - ubuntu-toolchain-r-test
          packages:
            - libclang-3.5-dev
            - llvm-3.5-dev
    - rust: stable
      env: CLANG_VERSION=clang_3_6 LLVM_CONFIG_PATH=/usr/lib/llvm-3.6/bin/llvm-config
      addons:
        apt:
          sources:
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.6
            - ubuntu-toolchain-r-test
          packages:
            - libclang-3.6-dev
            - llvm-3.6-dev
    - rust: stable
      env: CLANG_VERSION=clang_3_7 LLVM_CONFIG_PATH=/usr/lib/llvm-3.7/bin/llvm-config
      addons:
        apt:
          sources:
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
          packages:
            - libclang-3.7-dev
            - llvm-3.7-dev
    - rust: stable
      env: CLANG_VERSION=clang_3_8 LLVM_CONFIG_PATH=/usr/lib/llvm-3.8/bin/llvm-config
      addons:
        apt:
          sources:
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - libclang-3.8-dev
            - llvm-3.8-dev
    - rust: beta
      env: CLANG_VERSION=clang_3_8 LLVM_CONFIG_PATH=/usr/lib/llvm-3.8/bin/llvm-config
      addons:
        apt:
          sources:
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - libclang-3.8-dev
            - llvm-3.8-dev
    - rust: nightly
      env: CLANG_VERSION=clang_3_8 LLVM_CONFIG_PATH=/usr/lib/llvm-3.8/bin/llvm-config
      addons:
        apt:
          sources:
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - libclang-3.8-dev
            - llvm-3.8-dev
    - os: osx
      rust: stable
      env: LLVM_VERSION=devtools
    - os: osx
      rust: stable
      env: LLVM_VERSION=3.5 CLANG_VERSION=clang_3_5
    - os: osx
      rust: stable
      env: LLVM_VERSION=3.6 CLANG_VERSION=clang_3_6
    - os: osx
      rust: stable
      env: LLVM_VERSION=3.7 CLANG_VERSION=clang_3_7
    - os: osx
      rust: stable
      env: LLVM_VERSION=3.8 CLANG_VERSION=clang_3_8

before_install:
  -
    if [ "${TRAVIS_OS_NAME}" == "osx" ] && [ "${LLVM_VERSION}" != "devtools" ]; then
      brew update >/dev/null;
      brew install llvm3${LLVM_VERSION#3.};
    fi

before_script:
  -
    if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      if [ "${LLVM_VERSION}" != "devtools" ]; then
        export LLVM_CONFIG_PATH=`brew --prefix llvm3${LLVM_VERSION#3.}`/lib/llvm-${LLVM_VERSION}/bin/llvm-config;
      fi
    fi

script:
  -
    if [ "${LLVM_VERSION}" == "devtools" ]; then
        RUST_BACKTRACE=1 cargo test --verbose;
    else
        RUST_BACKTRACE=1 cargo test --verbose --features $CLANG_VERSION;
        if [ "${CLANG_VERSION}" != "clang_3_8" ]; then
            cargo clean;
            RUST_BACKTRACE=1 cargo test --verbose --features "$CLANG_VERSION static";
        fi
    fi
