language: rust

matrix:
  include:
    - rust: stable
      env: CLANG_VERSION=clang_3_5 LIBCLANG_PATH=/usr/lib/llvm-3.5/lib
      addons:
        apt:
          sources:
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.5
            - ubuntu-toolchain-r-test
          packages:
            - libclang-3.5-dev
            - llvm-3.5-dev
    - rust: stable
      env: CLANG_VERSION=clang_3_6 LIBCLANG_PATH=/usr/lib/llvm-3.6/lib
      addons:
        apt:
          sources:
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.6
            - ubuntu-toolchain-r-test
          packages:
            - libclang-3.6-dev
            - llvm-3.6-dev
    - rust: stable
      env: CLANG_VERSION=clang_3_7 LIBCLANG_PATH=/usr/lib/llvm-3.7/lib
      addons:
        apt:
          sources:
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
          packages:
            - libclang-3.7-dev
            - llvm-3.7-dev
    - rust: stable
      env: CLANG_VERSION=clang_3_8 LIBCLANG_PATH=/usr/lib/llvm-3.8/lib
      addons:
        apt:
          sources:
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - libclang-3.8-dev
            - llvm-3.8-dev
    - rust: beta
      env: CLANG_VERSION=clang_3_8 LIBCLANG_PATH=/usr/lib/llvm-3.8/lib
      addons:
        apt:
          sources:
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - libclang-3.8-dev
            - llvm-3.8-dev
    - rust: nightly
      env: CLANG_VERSION=clang_3_8 LIBCLANG_PATH=/usr/lib/llvm-3.8/lib
      addons:
        apt:
          sources:
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - libclang-3.8-dev
            - llvm-3.8-dev
    - os: osx
      rust: stable
      env: LLVM_VERSION=devtools CLANG_VERSION=clang_3_5
    - os: osx
      rust: stable
      env: LLVM_VERSION=3.8 CLANG_VERSION=clang_3_8

before_install:
  -
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      if [ "${LLVM_VERSION}" != "devtools" ]; then
        brew update >/dev/null;
        brew install llvm3${LLVM_VERSION#3.};
      fi
    fi

before_script:
  -
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      if [ "${LLVM_VERSION}" = "devtools" ]; then
        export LIBCLANG_PATH=/Library/Developer/CommandLineTools/usr/lib;
      else
        export LIBCLANG_PATH=`brew --prefix llvm3${LLVM_VERSION#3.}`/lib/llvm-${LLVM_VERSION}/lib;
      fi
    fi

script:
  -
    if [ "${TRAVIS_OS_NAME}" = "osx" ] && [ "${LLVM_VERSION}" == "devtools" ]; then
        RUST_BACKTRACE=1 cargo test --verbose;
    else
        RUST_BACKTRACE=1 cargo test --verbose --features $CLANG_VERSION;
    fi
