environment:
  matrix:
    - LLVM_VERSION: 3.8
      CLANG_VERSION: clang_3_8

install:
  - ps: .\ci\install.ps1
  - rustc --version
  - cargo --version

build: false

test_script:
  - SET RUST_BACKTRACE=1
  - cargo test --verbose --features %CLANG_VERSION% -- --nocapture
