[package]

name = "clang-sys"
authors = ["Kyle Mayes <kyle@mayeses.com>"]

version = "0.2.1"

readme = "README.md"
license = "Apache-2.0"

description = "Rust bindings for libclang."

documentation = "https://kylemayes.github.io/clang-sys/all/clang_sys"
repository = "https://github.com/KyleMayes/clang-sys"

build = "build.rs"

[features]

clang_3_5 = ["gte_clang_3_5"]
clang_3_6 = ["gte_clang_3_5", "gte_clang_3_6"]
clang_3_7 = ["gte_clang_3_5", "gte_clang_3_6", "gte_clang_3_7"]
clang_3_8 = ["gte_clang_3_5", "gte_clang_3_6", "gte_clang_3_7", "gte_clang_3_8"]

gte_clang_3_5 = []
gte_clang_3_6 = []
gte_clang_3_7 = []
gte_clang_3_8 = []

[dependencies]

bitflags = "0.4.0"
libc = "0.2.7"

[build-dependencies]

rustc_version = "0.1.6"
